title: Blender Realistic
description:

url: http://brianmaierjr.github.com/long-hau
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Tutorial
   url: /articles

social:
   github:
   twitter:
   facebook:
   email: varel260506@gmail.com

google_analytics: UA-67920972-4
